---

base_environment: develop

# Common options
#
apt_cache_valid_time: 86400
apt_install_packages: yes

# Setup postgresql
#
postgresql_databases:
  - { name: "{{base_project_name}}" }

postgresql_users:
  - { name: "{{base_project_name}}", pass: "{{base_project_name}}" }

postgresql_user_privileges:
  - name: "{{base_project_name}}"
    db: "{{base_project_name}}"
    priv: "ALL"

# Load source
# (Disable for vagrant of source directory mounted)
source_known_hosts: [github.com]
source_owner: "{{base_deploy_user}}"
source_sources:
  - repo: https://github.com/Stouts/Django-application.git
    dest: /usr/lib/{{base_project_name}}/source

wsgi_directory: "{{base_source_directory}}/{{base_project_name}}"
wsgi_hostname: "project.local"
wsgi_apt_packages:
  - postgresql-server-dev-all

django_app_path: "{{wsgi_directory}}"
django_settings_module: "main.settings.local"
django_settings_databases:
  - default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: "{{postgresql_databases.0.name}}"
      USER: "{{postgresql_users.0.name}}"
      PASSWORD: "{{postgresql_users.0.pass}}"
django_settings_caches:
  - default:
      BACKEND: redis_cache.cache.RedisCache
      LOCATION: "{{redis_bind}}:{{redis_port}}:1"
django_manage_list:
