---

# Stouts.deploy
# =============
deploy_app_name: project

# Stouts.apt
# ==========
apt_cache_valid_time: 86400
apt_install_packages: yes

# Ansibles.postgresql
# ===================
postgresql_databases:
  - { name: "{{base_project_name}}" }
postgresql_users:
  - { name: "{{base_project_name}}", pass: "{{base_project_name}}" }
postgresql_user_privileges:
  - name: "{{base_project_name}}"
    db: "{{base_project_name}}"
    priv: "ALL"

# Stouts.source
# =============
source_sources:
  - repo: https://github.com/Stouts/Django-application.git
    dest: "{{deploy_src_dir}}"

# Stouts.wsgi
# ===========
wsgi_nginx_servernames: "project.local"
wsgi_deb_packages:
  - postgresql-server-dev-all

# Stouts.django
# =============
django_settings_module: "main.settings.local"
django_settings_databases:
  - default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: "{{postgresql_databases.0.name}}"
      USER: "{{postgresql_users.0.name}}"
      PASSWORD: "{{postgresql_users.0.pass}}"
django_settings_caches:
  - default:
      BACKEND: redis_cache.cache.RedisCache
      LOCATION: "{{redis_bind}}:{{redis_port}}:1"
django_settings_additional:
    - BROKER_URL = 'redis://{{redis_bind}}:{{redis_port}}'
