---

base_environment: develop

# Common options
#
apt_cache_valid_time: 86400
apt_install_packages: yes

# Setup postgresql
#
postgresql_databases:
  - { name: "{{base_project_name}}" }

postgresql_users:
  - { name: "{{base_project_name}}", pass: "{{base_project_name}}" }

postgresql_user_privileges:
  - name: "{{base_project_name}}"
    db: "{{base_project_name}}"
    priv: "ALL"

source_known_hosts: [github.com]
source_owner: "{{base_deploy_user}}"
source_sources:
  - repo: https://github.com/Dipsomaniac/dj-simple.git
    dest: /usr/lib/simple/source

wsgi_directory: "{{base_source_directory}}/simple"

django_settings_module: "main.settings.local"
django_app_path: "{{base_source_directory}}/simple"
django_databases:
  - default:
      NAME: "{{postgresql_databases.0.name}}"
      USER: "{{postgresql_users.0.name}}"
      PASSWORD: "{{postgresql_users.0.pass}}"
