---

base_environment: vagrant

# source_enabled: no

wsgi_nginx_static_locations: []
wsgi_uwsgi_processes: 1
wsgi_uwsgi_reload: yes

django_manage_list:
    - collectstatic
    - syncdb
    - manage
    - create_devdata
